services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/laravel/public

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo' 
    volumes:
      - db_data:/var/lib/mysql
      - my.cnf:/etc/mysql/conf.d/my.cnf
      - sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes: 
  db_data:
  my.cnf:
  sql:
